/*
   Copyright (C) 2013 Mike Kipnis

   This file is part of QLDDS, a free-software/open-source library
   for utilization of QuantLib in the distributed envrionment via DDS.

   QLDDS is free software: you can redistribute it and/or modify it
   under the terms of the QLDDS license.  You should have received a
   copy of the license along with this program; if not, please email
   <dev@qldds.org>. The license is also available online at
   <http://qldds.org/qldds-license/>.

   This program is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
   FOR A PARTICULAR PURPOSE.  See the license for more details.
*/

#include <tao/orb.idl>

module SwaptionServer
{
  struct Swaption
  {
    string option_period;
    string swap_period;
    CORBA::StringSeq curve_components;
    string surface_name;
  };

  interface SwaptionCalculator
  {
    boolean CalculateATM( in Swaption option, out double npv, out double atm_rate, out string error ); 
  };
}; 
