
#pragma DCPS_DATA_TYPE "%(categoryName)s::%(functionName)s"
#pragma DCPS_DATA_KEY "%(categoryName)s::%(functionName)s instanceID" 

   @topic
   struct %(functionName)s { 
          @key string instanceID;
          %(idlDeclaration)s 
   };
